spring:
  application:
  name: mq
  jms:
    listener:
      min-concurrency: 10
    pub-sub-domain: false # Use Queue do not use topic
  mq:
    queue: DEV.QUEUE.1

  datasource:
    url: jdbc:mysql://localhost:3306/cap_samples
    username: capuser
    password: cappassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

ibm:
  mq:
    queue-manager: QM1
    channel: DEV.APP.SVRCONN
    conn-name: 192.168.1.108(1414)
    user: app
    password: passw0rd

